"""Architecture document data models.

Defines schemas for Strategy, Tactical Plan, ADR, and related architecture
artifacts generated by the framework. These models mirror the structure of
the proven HomeCare architecture document pipeline.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class DocumentStatus(str, Enum):
    """Architecture document lifecycle status."""

    DRAFT = "draft"
    PROPOSED = "proposed"
    APPROVED_FOR_DESIGN = "approved_for_design"
    APPROVED_FOR_IMPLEMENTATION = "approved_for_implementation"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"


class MermaidDiagram(BaseModel):
    """A Mermaid diagram embedded in an architecture document."""

    diagram_type: str = Field(..., description="Type: 'erDiagram', 'sequenceDiagram', 'C4Context', 'C4Container', 'C4Component', 'graph', 'stateDiagram-v2', 'gantt'.")
    title: str = Field(default="")
    content: str = Field(..., description="Raw Mermaid diagram code.")
    description: str = Field(default="", description="Explanation of what this diagram shows.")


class GapAnalysisItem(BaseModel):
    """An item in the gap analysis: what exists vs. what's needed."""

    capability: str = Field(..., description="The capability being assessed.")
    evidence: str = Field(default="", description="File paths or code references proving existence.")
    verdict: str = Field(..., description="'reuse', 'extend', 'build_new', 'defect'.")
    notes: str = Field(default="")


class RiskItem(BaseModel):
    """An entry in the risk register."""

    id: str = Field(..., description="Risk ID (e.g., R-01).")
    description: str
    likelihood: str = Field(..., description="'low', 'medium', 'high'.")
    impact: str = Field(..., description="'low', 'medium', 'high'.")
    mitigation: str
    owner: str = Field(default="")


class StrategyDocument(BaseModel):
    """Strategy Document model — mirrors the structure from the HomeCare architecture pipeline.

    Sections:
    1. Purpose and Scope (Executive Summary, In Scope, Out of Scope)
    2. Current-State Assessment (Reusable, Defects, New builds)
    3. Functional Requirements
    4. Non-Functional Requirements
    5. Constraints
    6. Assumptions
    7. Strategic Position
    8. Use Case Diagram (Mermaid)
    9. Sequence Diagrams (Mermaid)
    10. C4 Container Diagram (Mermaid)
    11. C4 Component Diagram (Mermaid)
    12. Domain State Machines (optional)
    13. Gap Analysis
    14. Risk Register
    15. Open Questions
    16. Execution Gate
    """

    feature_name: str
    version: str = Field(default="1.0")
    date: str = Field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d"))
    author: str = Field(default="Senior Solution Architect")
    status: DocumentStatus = Field(default=DocumentStatus.PROPOSED)
    related_adrs: list[str] = Field(default_factory=list)
    supersedes: str = Field(default="")

    # Content sections (rendered as markdown)
    executive_summary: str = Field(default="")
    in_scope: list[str] = Field(default_factory=list)
    out_of_scope: list[dict[str, str]] = Field(default_factory=list, description="List of {item, reason} dicts.")

    # Current-state assessment
    reusable_capabilities: list[GapAnalysisItem] = Field(default_factory=list)
    blocking_defects: list[dict[str, str]] = Field(default_factory=list, description="Defects that block the feature.")
    new_builds: list[str] = Field(default_factory=list)

    # Requirements (IDs reference FeatureRequest)
    functional_requirements_md: str = Field(default="", description="Full FR section as markdown.")
    non_functional_requirements_md: str = Field(default="", description="Full NFR section as markdown.")
    constraints_md: str = Field(default="")
    assumptions_md: str = Field(default="")

    # Strategy diagrams
    use_case_diagram: MermaidDiagram | None = None
    sequence_diagrams: list[MermaidDiagram] = Field(default_factory=list)
    c4_container_diagram: MermaidDiagram | None = None
    c4_component_diagram: MermaidDiagram | None = None
    state_machine_diagrams: list[MermaidDiagram] = Field(default_factory=list)

    # Analysis
    gap_analysis: list[GapAnalysisItem] = Field(default_factory=list)
    risk_register: list[RiskItem] = Field(default_factory=list)
    open_questions: list[dict[str, str]] = Field(default_factory=list)
    execution_gate: str = Field(default="")

    # Rendered output
    rendered_markdown: str = Field(default="", description="The complete rendered document.")


class ApiEndpoint(BaseModel):
    """An API endpoint specification in the tactical plan."""

    id: int
    method: str = Field(..., description="HTTP method: GET, POST, PUT, PATCH, DELETE.")
    route: str = Field(..., description="Route template (e.g., 'api/v{version}/vendor/bank-accounts').")
    handler: str = Field(default="", description="MediatR handler class name.")
    description: str = Field(default="")
    request_dto: str = Field(default="")
    response_dto: str = Field(default="")
    auth: str = Field(default="VendorPolicy", description="Authorization policy.")
    status_codes: list[int] = Field(default_factory=lambda: [200])


class FrontendRoute(BaseModel):
    """A frontend route specification."""

    path: str = Field(..., description="Route path (e.g., '/vendor/orders').")
    component: str = Field(default="", description="Primary component name.")
    render_strategy: str = Field(default="RSC", description="'RSC' (server) or 'client'.")
    description: str = Field(default="")
    child_components: list[str] = Field(default_factory=list)


class DatabaseTable(BaseModel):
    """A database table specification in the tactical plan."""

    name: str
    is_new: bool = Field(default=True, description="True if this is a new table, False if extending existing.")
    columns: list[dict[str, str]] = Field(default_factory=list, description="Column definitions.")
    indexes: list[str] = Field(default_factory=list, description="Index definitions.")
    check_constraints: list[str] = Field(default_factory=list)
    foreign_keys: list[str] = Field(default_factory=list)


class TacticalPlan(BaseModel):
    """Tactical Plan model — the implementation blueprint.

    Sections:
    1. Entity Relationship Diagram (Mermaid erDiagram)
    2. Database Schema Details (tables, indexes, constraints)
    3. Status Vocabularies and State Machines
    4. Migration Plan
    5. High-Level Design — Component Diagram
    6. API Endpoints
    7. Data Transfer Objects
    8. Frontend Route and Component Map
    9. Responsive and Accessibility Specification
    10. Work Package Breakdown
    11. Test Strategy
    12. Observability
    13. Definition of Done
    """

    feature_name: str
    version: str = Field(default="1.0")
    date: str = Field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d"))
    author: str = Field(default="Senior Solution Architect")
    status: DocumentStatus = Field(default=DocumentStatus.PROPOSED)
    companion_documents: list[str] = Field(default_factory=list)

    # Schema
    erd_diagram: MermaidDiagram | None = None
    database_tables: list[DatabaseTable] = Field(default_factory=list)
    status_vocabularies_md: str = Field(default="")
    migration_plan_md: str = Field(default="")

    # Design
    component_diagram: MermaidDiagram | None = None
    api_endpoints: list[ApiEndpoint] = Field(default_factory=list)
    dtos_md: str = Field(default="", description="DTO specifications as markdown.")
    frontend_routes: list[FrontendRoute] = Field(default_factory=list)
    responsive_spec_md: str = Field(default="")

    # Planning
    work_package_breakdown_md: str = Field(default="")
    test_strategy_md: str = Field(default="")
    observability_md: str = Field(default="")
    definition_of_done: list[str] = Field(default_factory=list)

    # Rendered
    rendered_markdown: str = Field(default="")


class ADRDecision(BaseModel):
    """A single decision within an ADR.

    Following the exhaustive format from ADR-021 where each decision
    has a code (D-01, D-02, ...), a title, the decision itself,
    rationale, and consequences.
    """

    code: str = Field(..., description="Decision code (e.g., 'D-01').")
    title: str = Field(..., description="Decision title.")
    decision: str = Field(..., description="What is being decided.")
    rationale: str = Field(..., description="Why this decision was made.")
    consequences: str = Field(default="", description="What becomes easier or harder.")


class ADRAlternative(BaseModel):
    """An alternative considered and rejected in an ADR."""

    name: str
    why_rejected: str


class ArchitectureDecisionRecord(BaseModel):
    """ADR model — following the exhaustive format from HomeCare ADR-021.

    Fields:
    - Status, Date, Deciders, Related ADRs, Scope
    - Context (the problem statement)
    - Decisions (multiple numbered D-XX decisions)
    - Alternatives Considered
    - Consequences (positive, negative, risks)
    - Compliance Notes
    - Validation criteria
    """

    number: int = Field(..., description="ADR number (e.g., 21).")
    title: str = Field(..., description="ADR title.")
    status: str = Field(default="Accepted", description="'Proposed', 'Accepted', 'Rejected', 'Deprecated', 'Superseded'.")
    date: str = Field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d"))
    deciders: list[str] = Field(default_factory=list)
    supersedes: str = Field(default="—")
    superseded_by: str = Field(default="—")
    related_adrs: list[str] = Field(default_factory=list)
    scope: str = Field(default="")

    # Content
    context: str = Field(..., description="What is the problem motivating this decision?")
    decisions: list[ADRDecision] = Field(default_factory=list, description="Individual numbered decisions.")
    alternatives_considered: list[ADRAlternative] = Field(default_factory=list)

    # Consequences
    positive_consequences: list[str] = Field(default_factory=list)
    negative_consequences: list[str] = Field(default_factory=list)
    risks_with_mitigation: list[dict[str, str]] = Field(default_factory=list)

    # Compliance
    compliance_notes: list[str] = Field(default_factory=list)

    # Validation
    validation_criteria: list[str] = Field(default_factory=list)

    # Rendered
    rendered_markdown: str = Field(default="")
