# Author: C A B M
# Date: 2026-09-17

"""Work package data models.

Defines the schema for work packages — self-contained, parallelisable
units of implementation work generated by the architect node and
executed by the code generation node.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class WaveId(str, Enum):
    """Well-known wave identifiers."""

    GATE = "gate"
    FOUNDATION = "foundation"
    WAVE_1 = "wave_1"
    WAVE_2 = "wave_2"
    WAVE_3 = "wave_3"
    VERIFICATION = "verification"


class WorkPackageStatus(str, Enum):
    """Execution status of a work package."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    BUILD_FAILED = "build_failed"
    TEST_FAILED = "test_failed"
    COMPLETED = "completed"
    SKIPPED = "skipped"
    FAILED = "failed"


class FileOwnership(BaseModel):
    """File-ownership entry for collision avoidance between work packages."""

    file_path: str = Field(..., description="Relative path from repo root.")
    exclusive_owner: str = Field(..., description="Work package ID that exclusively owns this file.")
    operation: str = Field(default="create", description="'create', 'modify', 'extend'.")


class WorkPackage(BaseModel):
    """A self-contained unit of implementation work.

    Each work package includes:
    - Scope definition
    - File ownership matrix
    - Dependencies on other work packages
    - The generated prompt to execute
    - Acceptance criteria
    - Execution results
    """

    id: str = Field(..., description="Work package ID (e.g., 'WP0', 'WP1').")
    title: str = Field(..., description="Descriptive title.")
    wave: str = Field(..., description="Execution wave this package belongs to.")
    owner_role: str = Field(default="", description="Suggested owner role (e.g., 'Backend Lead').")

    # Dependencies
    depends_on: list[str] = Field(default_factory=list, description="IDs of work packages this depends on.")
    is_blocking: bool = Field(default=False, description="If True, this must complete before any other WP in subsequent waves.")
    parallel_safe: bool = Field(default=True, description="If True, can run concurrently with other WPs in the same wave.")

    # Scope
    scope_description: str = Field(default="", description="What this work package delivers.")
    file_ownership: list[FileOwnership] = Field(default_factory=list)
    files_to_create: list[str] = Field(default_factory=list)
    files_to_modify: list[str] = Field(default_factory=list)

    # Prompt
    standing_instructions: str = Field(default="", description="Standing instructions prepended to the prompt.")
    prompt: str = Field(default="", description="The full generated prompt for this work package.")
    acceptance_criteria: list[str] = Field(default_factory=list)

    # Execution results
    status: WorkPackageStatus = Field(default=WorkPackageStatus.PENDING)
    generated_files: dict[str, str] = Field(default_factory=dict, description="file_path -> content.")
    build_output: str = Field(default="")
    test_output: str = Field(default="")
    error_message: str = Field(default="")
    attempt_count: int = Field(default=0)

    # Estimated effort
    estimated_days: float = Field(default=0.0)


class ExecutionWave(BaseModel):
    """A group of work packages that can execute concurrently."""

    wave_id: str = Field(..., description="Wave identifier.")
    name: str = Field(default="")
    work_packages: list[WorkPackage] = Field(default_factory=list)
    max_concurrent: int = Field(default=5)
    is_gate: bool = Field(default=False, description="If True, must fully complete before next wave.")


class ExecutionPlan(BaseModel):
    """The complete execution plan: ordered waves of work packages."""

    feature_name: str
    waves: list[ExecutionWave] = Field(default_factory=list)
    file_ownership_matrix: list[FileOwnership] = Field(default_factory=list)
    standing_instructions: str = Field(default="")

    @property
    def total_work_packages(self) -> int:
        """Total number of work packages across all waves."""
        return sum(len(w.work_packages) for w in self.waves)

    @property
    def completed_count(self) -> int:
        """Number of completed work packages."""
        return sum(
            1
            for w in self.waves
            for wp in w.work_packages
            if wp.status == WorkPackageStatus.COMPLETED
        )
